### ISSUE TITLE
Crash upon placing the Ki-61

### ISSUE THREAD

**Issue by technodante** [technodante/technodante-axis-pack#1]
This is a bug which happens by placing the Ki-61 into a Minecraft world. When it is placed, the game freezes and subsequently crashes. An affected world can still be accessed after the crash, however, the Ki-61 will not be present on the block you originally placed it on. This error appears to be caused by a bug in Ki61.txt, since the error message references DriveableType.
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 2/26/21 10:27 PM
Description: Ticking memory connection

java.lang.NullPointerException: Ticking memory connection
	at com.flansmod.common.driveables.EntityWheel.initPosition(EntityWheel.java:53)
	at com.flansmod.common.driveables.EntityWheel.<init>(EntityWheel.java:48)
	at com.flansmod.common.driveables.EntityDriveable.initType(EntityDriveable.java:257)
	at com.flansmod.common.driveables.EntityPlane.initType(EntityPlane.java:110)
	at com.flansmod.common.driveables.EntityPlane.<init>(EntityPlane.java:97)
	at com.flansmod.common.driveables.EntityPlane.<init>(EntityPlane.java:102)
	at com.flansmod.common.driveables.ItemPlane.onItemRightClick(ItemPlane.java:153)
	at net.minecraft.item.ItemStack.useItemRightClick(ItemStack.java:164)
	at net.minecraft.server.management.ItemInWorldManager.tryUseItem(ItemInWorldManager.java:345)
	at net.minecraft.network.NetHandlerPlayServer.processPlayerBlockPlacement(NetHandlerPlayServer.java:576)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.processPacket(C08PacketPlayerBlockPlacement.java:74)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.processPacket(C08PacketPlayerBlockPlacement.java:122)
	at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:241)
	at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:182)
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:726)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:614)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:118)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:485)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:752)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.flansmod.common.driveables.EntityWheel.initPosition(EntityWheel.java:53)
	at com.flansmod.common.driveables.EntityWheel.<init>(EntityWheel.java:48)
	at com.flansmod.common.driveables.EntityDriveable.initType(EntityDriveable.java:257)
	at com.flansmod.common.driveables.EntityPlane.initType(EntityPlane.java:110)
	at com.flansmod.common.driveables.EntityPlane.<init>(EntityPlane.java:97)
	at com.flansmod.common.driveables.EntityPlane.<init>(EntityPlane.java:102)
	at com.flansmod.common.driveables.ItemPlane.onItemRightClick(ItemPlane.java:153)
	at net.minecraft.item.ItemStack.useItemRightClick(ItemStack.java:164)
	at net.minecraft.server.management.ItemInWorldManager.tryUseItem(ItemInWorldManager.java:345)
	at net.minecraft.network.NetHandlerPlayServer.processPlayerBlockPlacement(NetHandlerPlayServer.java:576)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.processPacket(C08PacketPlayerBlockPlacement.java:74)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.processPacket(C08PacketPlayerBlockPlacement.java:122)
	at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:241)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@66412e26
Stacktrace:
	at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:182)
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:726)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:614)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:118)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:485)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:752)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_271, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3489903824 bytes (3328 MB) / 4225236992 bytes (4029 MB) up to 4225236992 bytes (4029 MB)
	JVM Flags: 3 total; -Xincgc -Xmx4G -Xms4G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forgeSrc-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1558} [Minecraft Forge] (forgeSrc-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJAAAA	examplemod{1.0} [Example Mod] (bin) 
	UCHIJAAAA	flansmod{@VERSION@} [Flan's Mod Ultimate] (bin) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['Player776'/37, l='New World', x=206.49, y=69.00, z=-62.68]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by technodante** [comment]
Solution: Replace improperly used commas in Ki-61.txt with periods.
